version: '3.8'

services:
    app:
        image: 0.0.1
        user: "1000:1000"
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8082:80"
        environment:
            - SERVER_PORT=8082
        networks:
            - test
        command: php artisan queue:work
    db:
        image: mysql:8.0
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: apps
            MYSQL_ROOT_PASSWORD: 2003
        ports:
            - "3308:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: db
        networks:
            - test


# Volumes
volumes:
    db-data:
        driver: local
networks:
    test:
        driver: bridge

